### PR TITLE
chore: Prepare release 1.1.0

### PR DESCRIPTION
**Pull request by miquelbeltran**
### Description :memo:

- **Purpose**: Prepare release 1.1.0
- **Approach**: Bump version and Changelog

**Type of change**

- [x] new release

**Updates**

- Bump versions on all csproj files
- Created CHANGELOG.md on repo root

Once approved, I will proceed with the Nuget package build and merge.

### Test plan :test_tube:

- None

### Author to check :eyeglasses:

- [ ] Project and all contained modules builds successfully
- [ ] Self-/dev-tested
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

### Reviewer to check :heavy_check_mark:

- [ ] Project and all contained modules builds successfully
- [ ] Change has been dev-/reviewer-tested, where possible
- [ ] Unit/UI/Automation/Integration tests provided where applicable
- [ ] Code is written to standards
- [ ] Appropriate documentation written (code comments, internal docs)

### CODE REVIEW

**Comment by miquelbeltran** [comment]
Thanks!

I see an issue with CI: 
```
error NETSDK1139: The target platform identifier android was not recognized. [D:\a\raygun4blazor\raygun4blazor\src\Raygun.Samples.Blazor.Maui\Raygun.Samples.Blazor.Maui.csproj::TargetFramework=net8.0-android]
```

I don't think this would stop the release, but I will check tomorrow any case.

**Review by sumitramanga — APPROVED** [review]
LGTM! :shipit:

**Comment by sumitramanga** [comment]
@miquelbeltran There's something failing - Build & test check. was this already broken or broke in this branch? If always broken you can merge otherwise please fix it up in this branch if it's related

**Comment by miquelbeltran** [comment]
Packages have been published! 🎉 tomorrow I will research why GitHub CI complained about the MAUI Sample android config

**Pull request merged**
